// react-native-localization replaced with a plain object wrapper
// that matches the same API used across screens (Strings.SomeKey)
const Strings = {
  AppName: 'Kingdom Solutions',
  EmailAddress: 'Email Address',
  UserName: 'User Name',
  Password: 'Password',
  SIGNIN: 'SIGN IN',
  SETMPIN: 'SET MPIN',
  SetMPin: 'Set MPIN',
  SetPinMessage:
    'Set the MPIN for the authenticated access now onward. You just need to enter a 4-digit MPIN to access the app.',
  EnterPinMessage:
    'Enter the MPIN as you set last time to access the app.',
  ERPNo: 'ERP Order No.',
  SwitchDriverApp: 'Switch To Driver App',
  AddNewCustomer: 'Add New Customer',
  AppVersion: 'App Version V',
  CustomerInformation: 'Customer Information',
  ScheduleDate: 'Schedule Date',
  OrderDate: 'Order Date',
  OrderType: 'Order Type',
  Cash: 'Cash',
  Credit: 'Credit',
  AddItem: 'Add Item',
  Specs: 'Specs',
  Ice: 'Ice',
  Pump: 'Pump',
  PipeFixing: 'Pipe Fixing',
  Transport: 'Transport',
  Quantity: 'Quantity',
  Discount: 'Discount',
  Time: 'Time',
  PlacingDate: 'Placing Date',
  Remark: 'Remark',
  CustomerName: 'Customer Name',
  CustomerCode: 'Customer Code',
  PhoneNo: 'Phone No',
  Edit: 'Edit',
  Del: 'Delete',
  EditItem: 'Edit Item',
  ScheduleTime: 'Schedule Time',
  CustomerType: 'Customer Type',
  ResetMPin: 'Forgot MPIN?',
  EmailNullError: 'Email Address should not be empty.',
  InvalidEmailError: 'Enter valid Email Address.',
  Signature: 'Signature',
  SignatureMessage: 'Sign in the area between dashed border.',
  CustomerNameNullError: 'Customer Name should not be empty.',
  CustomerCodeNullError: 'Customer Code should not be empty.',
  CustomerPhoneNullError: 'Phone Number should not be 0 or empty.',
  CustomerTypeNullError: 'Select any Customer Type.',
  SiteNullError: 'Select or Enter any Site',
  ScheduleTimeInvalidError: 'Select futuristic Schedule Date or Time.',
  DivisionNullError: 'Select Division.',
  StockNullError: 'Select Stock Item.',
  QuantityNullError: 'Quantity should not be null or zero.',
  DiscountNullError: 'Discount should not be null or zero.',
  TimeUpMessage: 'This Order cannot be editable now.',
  EmptySignatureError: 'Signature field should not be empty.',
  CannotSendOnWatsapp: 'Cannot send to Whatsapp as Mobile number is empty.',
  WatsappMobileNo: 'Whatsapp/Mobile Number',
  SendEmail: 'Send Email',
  SendWhatsapp: 'Send Whatsapp',
  Reset: 'Reset',
  ShareViaWhatsApp: 'Share Via Whatsapp',
  ShareViaEmail: 'Share Via Email',
  TakeSignature: 'Take Signature',
  NeedReciept: 'Need A Reciept',
  DeleteOrderRemark: '* Enter the Remark Before Delete the Order.',
  PendingQty: 'Pen. Qty',
  saveOrder: 'Save Order',
  syncOrder: 'Sync',
};

export default Strings;
